#!/usr/bin/python

# i3 config generator/switcher
# by Oliver Kraitschy
# http://okraits.de okraits@arcor.de

from os import path, getenv, listdir, system
from sys import argv

# global variables
SYSTEM_THEME_PATH = "/usr/share/j4-make-config-git/themes"
THEME_PATH = ""
i3_PATH = ""
i3_BASECONFIG = ""
i3_CONFIG = ""
noTheme = False
restart_arg = 0
theme_arg = 0
windowActive = False
barActive = False
windowText = ""
barText = ""

def detectConfigDir():
	global i3_PATH
	if path.exists(getenv("HOME") + "/.i3/config"):
		i3_PATH = getenv("HOME") + "/.i3"
		return True
	if getenv("XDG_CONFIG_HOME") is not None:
		if path.exists(getenv("XDG_CONFIG_HOME") + "/i3/config"):
			i3_PATH = getenv("XDG_CONFIG_HOME") + "/i3"
			return True
	if path.exists(getenv("HOME") + "/.config/i3/config"):
		i3_PATH = getenv("HOME") + "/.config/i3"
		return True
	else:
		return False

def printUsageInfo():
	info = """i3 config generator/switcher\n
Usage:
======
Set a specific theme:
\tj4-make-config <theme-name>
Create config file without including a theme:
\tj4-make-config none
Restart i3 after creating the config file:
\tj4-make-config -r <theme-name>|none"""
	print(info)

def printThemeList():
	print("\nAvailable themes:")
	print("=================")
	print("\n".join(sorted(themes.keys())))

if __name__ == "__main__":
	# detect i3 configuration directory
	if not detectConfigDir():
		print("Error: i3 config file could not be found.")
		exit(1)
	else:
		# set paths
		THEME_PATH = i3_PATH + "/themes"
		i3_BASECONFIG = i3_PATH + "/config.base"
		i3_CONFIG = i3_PATH + "/config"
		# fill themes dictionary with names and paths
		themes = {}
		try:
			if path.exists(SYSTEM_THEME_PATH):
				for theme in listdir(SYSTEM_THEME_PATH):
					themes[theme] = SYSTEM_THEME_PATH + "/" + theme
			if path.exists(THEME_PATH):
				for theme in listdir(THEME_PATH):
					themes[theme] = THEME_PATH + "/" + theme
		except (IOError, OSError):
			print("Error: No themes found.")
			exit(1)
	
	# parse cli arguments
	if (len(argv) == 1):
		# in the future we'll use the previously used options here
		print("Nothing to do.")
		exit(0)
	elif (len(argv) == 2):
		if (argv[1] == "-h" or argv[1] == "--help"):
			printUsageInfo()
			printThemeList()
			exit(0)
		else:
			theme_arg = 1
	elif (len(argv) == 3):
		if argv[1] == "-r":
			restart_arg = 1
			theme_arg = 2
		elif argv[2] == "-r":
			restart_arg = 2
			theme_arg = 1
		else:
			# wrong number of cli arguments
			printUsageInfo()
			printThemeList()
			exit(1)
	else:
		# wrong number of cli arguments
		printUsageInfo()
		printThemeList()
		exit(1)
	
	# we must not include a theme in the config file
	if argv[1] == "none":
		noTheme = True
	
	if not noTheme:
		# try to open given filename
		try:
			themefile = open(themes[argv[theme_arg]], "r")
		except (KeyError, IOError):
			print("Error: given theme does not exist.")
			printThemeList()
			exit(1)
		
		# read themefile, create section strings
		for line in themefile:
			if "$i3-theme-window" in line:
				windowActive = True
				barActive = False
			elif "$i3-theme-bar" in line:
				windowActive = False
				barActive = True
			else:
				if windowActive and not barActive:
					windowText += line
				elif not windowActive and barActive:
					barText += line
		themefile.close()
	
	# try to open i3 base config file
	try:
		basefile = open(i3_BASECONFIG, "r")
	except IOError:
		print("Error: i3 base config file does not exist.")
		exit(1)
	
	# try to open i3 config file
	try:
		configfile = open(i3_CONFIG, "w")
	except IOError:
		print("Error: i3 config file does not exist.")
		exit(1)
	
	# read base config file, write content to config file
	# and insert theme config at the right place
	for line in basefile:
		if "$i3-theme-window" in line:
			if not noTheme:
				configfile.write(windowText)
		elif "$i3-theme-bar" in line:
			if not noTheme:
				configfile.write(barText)
		else:
			configfile.write(line)
	basefile.close()
	configfile.flush()
	configfile.close()

	if restart_arg > 0:
		system("i3-msg restart")
	
	exit(0)
